name         'akquinet-postgresql'
version      '1.1.0'
source       'https://github.com/akquinet/puppet-postgresql.git'
author       'saheba'
license      'ASL 2.0'
summary      'Manage postgresql installations'
description  'Manage postgresql installations'
project_page 'https://github.com/akquinet/puppet-postgresql'
